### PR TITLE
Hotfix/cors error

### PR DESCRIPTION
**Pull request by Vuurvos1**
Fixed cors error using a proxy

### CODE REVIEW

**Comment by Vuurvos1** [comment]
This might need more testing before merging to ensure it works properly

**Comment by instafluff** [comment]
Looks like it works! I'll merge it for now and see. I would like to revert the code formatting changes though if that is okay.

**Comment by Vuurvos1** [comment]
No problem if you revert the code formatting! I just really like my singe quotes 😉 , I will pay more attention to keep the current code formatting next time I make a contribution

**Comment by instafluff** [comment]
Done! It's still a bit frankenstein-y since the code formatting's not consistent throughout and wasn't before either but this is awesome! Thank you so much for this hotfix!

**Comment by Vuurvos1** [comment]
You could install a tool like [ESlint ](https://eslint.org/) in your projects that keeps formatting between code consistent. It allows you to set up your own code standards or use existing ones, and use a command to format all files according to this standard.

**Pull request merged**
